something/main/urls.py
from django.urls import path
from .views import main_page, PostCreateView

urlpatterns = [
    path('', main_page, name='main'),
    path('/create-post', PostCreateView.as_view(), name='create-post'),
]

something/something/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

something/main/models.py
import datetime
from sqlite3 import IntegrityError

from django.db import models

# Create your models here.
from django.utils.text import slugify


class Post(models.Model):

    title = models.CharField('Title', blank=False, max_length=56, default=None)
    description = models.CharField('Description', blank=False, max_length=512, default=None)
    author = models.CharField('Author\'s name', max_length=56, blank=False, default='Anonymous')
    image = models.ImageField('Image', max_length=56, blank=False, default="Noimage.png")
    created_date = models.DateTimeField(blank=True, default=datetime.datetime.now)
    slug = models.SlugField('Slug', max_length=56, unique=False)

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        self.slug = slugify([self.title])
        super(Post, self).save(**kwargs)

    def get_absolute_url(self):
        return f"/project/{self.slug}/{self.id}"

something/main/forms.py
from django.forms import ModelForm, forms
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description", "author", "image"]

something/main/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from .forms import PostForm
from .models import Post


def main_page(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'main/main.html', context=context)


class PostCreateView(generic.CreateView):
    form_class = PostForm
    template_name = 'main/create_post.html'

    def post(self, request, *args, **kwargs):
        post = PostForm(request.POST, request.FILES)
        if post.is_valid():
            post.save()
        else:
            return HttpResponse("Error")
        return redirect('main')

something/main/templates/main/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'main/img/icon.png' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    {% block links %}{% endblock %}
</head>
<body>
    <div class="body-container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
              <svg class="bi me-2" width="40" height="32"></svg>
              <img class="header-icon" src="{% static 'main/svg/icon.svg' %}" alt="">
              <span class="fs-4">Something</span>
            </a>
      
            <ul class="nav nav-pills">
              <li class="nav-item"><a href="{% url 'main' %}" id="main-nav-link" class="nav-link active" aria-current="page">Home</a></li>
              <li class="nav-item"><a href="{% url 'create-post' %}" id="create-post-nav-link" class="nav-link">Create post</a></li>
              <li class="nav-item"><a href="https://github.com/IHateModernity" target="_blank" class="nav-link">Git</a></li>
              <li class="nav-item"><a href="https://www.linkedin.com/in/mark-semikhov/" target="_blank" class="nav-link">LinkedIn</a></li>
              <li class="nav-item"><a href="https://www.projectm.space/" target="_blank" class="nav-link">Other Django Projects</a></li>
            </ul>
        </header>
        {% block content %}{% endblock %}
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <p class="col-md-4 mb-0 text-body-secondary">© 2024 Something Inc</p>
        
            <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <img class="header-icon" src="{% static 'main/svg/icon.svg' %}" alt="">
            </a>
        
            <ul class="nav col-md-4 justify-content-end">
              <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
              <li class="nav-item"><a href="https://github.com/IHateModernity" target="_blank" class="nav-link px-2 text-body-secondary">Git</a></li>
              <li class="nav-item"><a href="https://www.linkedin.com/in/mark-semikhov/" target="_blank" class="nav-link px-2 text-body-secondary">LinkedIn</a></li>
            </ul>
          </footer>
    </div>
</body>
</html>

something/main/templates/main/create_post.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}New post{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static 'main/css/create_post.css' %}">

    <script>
        function setActive() {
            var element = document.getElementById("create-post-nav-link");
            var element2 = document.getElementById("main-nav-link")
            element.classList.add("active");
            element2.classList.remove("active")
        }

        document.addEventListener("DOMContentLoaded", function(){
            setActive();
        });
    </script>
{% endblock %}

{% block content %}
<main>
    <div class="form-box">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-line form-group">
                <label for="id_title">Title:</label>
                <input class="form-control" type="text" name="title" maxlength="56" required="" id="id_title">
            </div>
        
            <div class="form-line form-group">
                <label for="id_description">Description:</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" type="text" name="description" maxlength="512" required="" id="id_description"></textarea>
            </div>
        
            <div class="form-line form-group">
                <label for="id_author">Author's name:</label>
                <input class="form-control" type="text" name="author" value="Anonymous" maxlength="56" required="" id="id_author">
            </div>

            <div class="form-line form-group">
                <label for="id_image">Title:</label>
                <input class="form-control" type="file" name="image" maxlength="56" required="" id="id_image" accept="image/*">
            </div>

            <div class="form-line">
                <button class="btn btn-success" type="submit">Create</button>    
            </div>
            
        </form>
    </div>
</main>
{% endblock %}

something/main/templates/main/main.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Something{% endblock %}

{% block content %}
    <main>
        <div class="container px-4 py-5" id="custom-cards">
            <h2 class="pb-2 border-bottom">Some data from database:</h2>

            <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
              {% for post in posts %}
                <div class="col">
                  <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('{% get_media_prefix %}{{ post.image }}');">
                    <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                      <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">{{ post.title }}</h3>
                      <small>{{ post.description|slice:":40" }}...</small>
                      <ul class="d-flex list-unstyled mt-auto">
                        <li class="me-auto" >
                          <img src="{% static 'main/img/icon.png' %}" style="background-color: white;" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
                        </li>
                        <li class="d-flex align-items-center me-3">
                          <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
                          <small>{{ post.author|slice:":20" }}</small>
                        </li>
                        <li class="d-flex align-items-center">
                          <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"></use></svg>
                          <small>{{ post.created_date }}</small>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
    </main>
{% endblock %}